### ISSUE TITLE
Docker image/repository not available

### ISSUE THREAD

**Issue by lilic** [brendandburns/kubesanity#2]
While following the instructions in the `README`, it seems like the repository does not exist or is private:

```
✗ docker pull brendanburns/kube-sanity:0.1.0
Error response from daemon: pull access denied for brendanburns/kube-sanity, repository does not exist or may require 'docker login'
```

**Comment by brendandburns** [comment]
argh, sorry, need to push it...

**Comment by brendandburns** [comment]
Ok, it's pushed now.  Sorry about that!

**Comment by lilic** [comment]
@brendandburns No worries, thank you! Nice project!

**Comment by lilic** [comment]
@brendandburns Hello, it's me again. 😄 I get the same error, tried on multiple machines but it seems like the repo is not available yet....

**Comment by brendandburns** [comment]
Argh, sorry there's a typo in the image name, it shouldn't have the dash...

https://hub.docker.com/r/brendanburns/kubesanity/

I'll fix the docs

Sorry!

**Comment by lilic** [comment]
@brendandburns Thanks! All good now! :)
